services:
  mysql:
    image: mysql:8.0
    container_name: citas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: citas_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - citas_net

  ms-usuarios:
    build: ./ms-usuarios
    container_name: ms_usuarios
    restart: unless-stopped
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - citas_net

  ms-especialidades:
    build: ./ms-especialidades
    container_name: ms_especialidades
    restart: unless-stopped
    environment:
      PORT: 3007
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - citas_net

  ms-disponibilidad:
    build: ./ms-disponibilidad
    container_name: ms_disponibilidad
    restart: unless-stopped
    environment:
      PORT: 3003
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
      MS_USUARIOS_URL: http://ms-usuarios:3001
      MS_ESPECIALIDADES_URL: http://ms-especialidades:3007
    depends_on:
      mysql:
        condition: service_healthy
      ms-usuarios:
        condition: service_started
      ms-especialidades:
        condition: service_started
    networks:
      - citas_net

  ms-citas:
    build: ./ms-citas
    container_name: ms_citas
    restart: unless-stopped
    environment:
      PORT: 3004
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
      MS_USUARIOS_URL: http://ms-usuarios:3001
      MS_DISPONIBILIDAD_URL: http://ms-disponibilidad:3003
      MS_HISTORIAL_URL: http://ms-historial:3005
    depends_on:
      mysql:
        condition: service_healthy
      ms-usuarios:
        condition: service_started
      ms-disponibilidad:
        condition: service_started
      ms-historial:
        condition: service_started
    networks:
      - citas_net

  ms-historial:
    build: ./ms-historial
    container_name: ms_historial
    restart: unless-stopped
    environment:
      PORT: 3005
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - citas_net

  ms-gateway:
    build: ./ms-gateway
    container_name: ms_gateway
    restart: unless-stopped
    environment:
      PORT: 8080
      MS_USUARIOS_URL: http://ms-usuarios:3001
      MS_DISPONIBILIDAD_URL: http://ms-disponibilidad:3003
      MS_CITAS_URL: http://ms-citas:3004
      MS_HISTORIAL_URL: http://ms-historial:3005
      MS_ESPECIALIDADES_URL: http://ms-especialidades:3007
      MS_AUTH_URL: http://ms-auth:3006
    ports:
      - "8080:8080"
    depends_on:
      - ms-usuarios
      - ms-disponibilidad
      - ms-citas
      - ms-historial
      - ms-especialidades
      - ms-auth
    networks:
      - citas_net

  ms-auth:
    build: ./ms-auth
    container_name: ms_auth
    restart: unless-stopped
    environment:
      PORT: 3006
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: citas_db
      JWT_SECRET: super_secret_dev_key
      JWT_EXPIRES: 8h
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - citas_net

  ms-frontend:
    build: ./ms-frontend
    container_name: ms_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - ms-gateway
    networks:
      - citas_net

networks:
  citas_net:
    driver: bridge

volumes:
  mysql_data:
